### ISSUE TITLE
TabError / No output

### ISSUE THREAD

**Issue by heaversm** [valillon/FaceMorph#1]
Installed dependencies seemingly without error. Getting the following output

<img width="573" alt="screen shot 2019-02-05 at 1 27 10 pm" src="https://user-images.githubusercontent.com/520541/52305400-dd14f380-2949-11e9-92b7-b583497f2f47.png">

Ubuntu

**Comment by valillon** [comment]
Converted indentation to spaces in this commit [#213e29aa](https://github.com/valillon/FaceMorph/commit/213e29aac7a415851e6a6c9ff5cbad043e40664d).
Thanks!
