### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by heaversm** [valillon/FaceMorph#2]
Manually fixed the indentation, now I'm at:

```
Traceback (most recent call last):
  File "landmark_detector.py", line 67, in <module>
    f.write(str(x) + ' ' + str(y) + '\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by heaversm** [comment]
Figured this out - python 3 vs python 2. In python3, it should be `f = open(landmarks_file, 'w')`. And also in `faceMorph.py` any instance of `xrange` should be `range`.

**Comment by valillon** [comment]
Added to the readme that python 2 is required.
Thanks!
